/**
 * List of Vietnamese banks
 * Source: State Bank of Vietnam (SBV) official bank codes
 */
const VIETNAMESE_BANKS = [
  { code: "970405", name: "Ngân hàng TMCP Công thương Việt Nam", shortName: "VietinBank" },
  { code: "970436", name: "Ngân hàng TMCP Ngoại thương Việt Nam", shortName: "Vietcombank" },
  { code: "970418", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam", shortName: "BIDV" },
  { code: "970422", name: "Ngân hàng TMCP Quân đội", shortName: "MB Bank" },
  { code: "970407", name: "Ngân hàng TMCP Kỹ thương Việt Nam", shortName: "Techcombank" },
  { code: "970416", name: "Ngân hàng TMCP Á Châu", shortName: "ACB" },
  { code: "970432", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", shortName: "VPBank" },
  { code: "970423", name: "Ngân hàng TMCP Tiên Phong", shortName: "TPBank" },
  { code: "970403", name: "Ngân hàng TMCP Sài Gòn Thương Tín", shortName: "Sacombank" },
  { code: "970419", name: "Ngân hàng TMCP Quốc Dân", shortName: "NCB" },
  { code: "970415", name: "Ngân hàng TMCP Công thương Việt Nam", shortName: "VietinBank" },
  { code: "970441", name: "Ngân hàng TMCP Quốc tế Việt Nam", shortName: "VIB" },
  { code: "970443", name: "Ngân hàng TMCP Sài Gòn - Hà Nội", shortName: "SHB" },
  { code: "970431", name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam", shortName: "Eximbank" },
  { code: "970448", name: "Ngân hàng TMCP Phương Đông", shortName: "OCB" },
  { code: "970414", name: "Ngân hàng TMCP Đại Dương", shortName: "OceanBank" },
  { code: "970433", name: "Ngân hàng TMCP Việt Á", shortName: "VietABank" },
  { code: "970438", name: "Ngân hàng TMCP Bưu Điện Liên Việt", shortName: "LienVietPostBank" },
  { code: "970454", name: "Ngân hàng TMCP Việt Nam Thương Tín", shortName: "Vietbank" },
  { code: "970437", name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh", shortName: "HDBank" },
  { code: "970449", name: "Ngân hàng TMCP Bản Việt", shortName: "VietCapitalBank" },
  { code: "970439", name: "Ngân hàng TMCP Bắc Á", shortName: "BacABank" },
  { code: "970429", name: "Ngân hàng TMCP Sài Gòn Công Thương", shortName: "SaigonBank" },
  { code: "970434", name: "Ngân hàng TMCP Đông Nam Á", shortName: "SeABank" },
  { code: "970440", name: "Ngân hàng TMCP Sài Gòn", shortName: "SCB" },
  { code: "970426", name: "Ngân hàng TMCP Hàng Hải Việt Nam", shortName: "MSB" },
  { code: "970421", name: "Ngân hàng TMCP Kiên Long", shortName: "KienlongBank" },
  { code: "970427", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", shortName: "VietBank" },
  { code: "970430", name: "Ngân hàng TMCP Xăng dầu Petrolimex", shortName: "PG Bank" },
  { code: "970425", name: "Ngân hàng TMCP An Bình", shortName: "ABBANK" },
  { code: "970406", name: "Ngân hàng TMCP Đông Á", shortName: "DongA Bank" },
  { code: "970424", name: "Ngân hàng TMCP Sài Gòn - Hà Nội", shortName: "ShinhanBank" },
  { code: "970410", name: "Ngân hàng TNHH MTV Standard Chartered Việt Nam", shortName: "Standard Chartered" },
  { code: "970412", name: "Ngân hàng TNHH MTV Public Việt Nam", shortName: "Public Bank" },
  { code: "970413", name: "Ngân hàng TNHH MTV HSBC Việt Nam", shortName: "HSBC" },
  { code: "970409", name: "Ngân hàng TNHH MTV Woori Việt Nam", shortName: "Woori Bank" },
  { code: "970408", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", shortName: "Hong Leong Bank" },
  { code: "970452", name: "Ngân hàng Liên doanh VID Public", shortName: "VID Public" },
  { code: "970457", name: "Ngân hàng TNHH MTV Woori Việt Nam", shortName: "Woori" },
  { code: "970458", name: "Ngân hàng United Overseas Bank Việt Nam", shortName: "UOB" },
  { code: "546034", name: "Ngân hàng TMCP Đại Chúng Việt Nam", shortName: "PVcomBank" },
  { code: "970446", name: "Ngân hàng Hợp tác xã Việt Nam", shortName: "Co-opBank" },
  { code: "970450", name: "Ngân hàng TNHH MTV Công nghiệp Hàn Quốc", shortName: "IBK" },
  { code: "970455", name: "Ngân hàng TNHH MTV Shinhan Việt Nam", shortName: "Shinhan Bank" },
  { code: "970456", name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB" },
  { code: "970460", name: "Ngân hàng Kookmin - CN Hà Nội", shortName: "Kookmin Bank" },
  { code: "970462", name: "Ngân hàng TNHH MTV HSBC Việt Nam", shortName: "HSBC Vietnam" },
  { code: "422589", name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB VN" },
];

module.exports = {
  VIETNAMESE_BANKS,
};
