module.exports = {
  User: require("./user.model"),
  Subject: require("./subject.model"),
  Document: require("./document.model"),
  QuestionSet: require("./questionSet.model"),
  QuizAttempt: require("./quizAttempt.model"),
  ValidationRequest: require("./validationRequest.model"),
  CommissionRecord: require("./commissionRecord.model"),
  SubscriptionPlan: require("./subscriptionPlan.model"),
  UserSubscription: require("./userSubscription.model"),
  Notification: require("./notification.model"),
  RefreshToken: require("./refreshToken.model"),
  PasswordResetToken: require("./passwordResetToken.model"),
  UsageTracking: require("./usageTracking.model"),
  AddonPackage: require("./addonPackage.model"),
  UserAddonPurchase: require("./userAddonPurchase.model"),
  ProcessedTransaction: require("./processedTransaction.model"),
};
